// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuxiKCNE8A2o2ayuWbvwZodM3eok82xSM',
    appId: '1:338447448847:web:22dd137fc2f3f097a25c7a',
    messagingSenderId: '338447448847',
    projectId: 'redline-92e12',
    authDomain: 'redline-92e12.firebaseapp.com',
    storageBucket: 'redline-92e12.appspot.com',
    measurementId: 'G-X0QH25WMF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLlbosOwXIKVhNasrPgtDJpKRG6JroxRU',
    appId: '1:338447448847:android:79bb8517ccdd5cf8a25c7a',
    messagingSenderId: '338447448847',
    projectId: 'redline-92e12',
    storageBucket: 'redline-92e12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiEHgikQ6I78Khz7VVuaLEYQwqk82ZVVk',
    appId: '1:338447448847:ios:51fec46c5b0b9631a25c7a',
    messagingSenderId: '338447448847',
    projectId: 'redline-92e12',
    storageBucket: 'redline-92e12.appspot.com',
    iosBundleId: 'com.example.redLineTut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiEHgikQ6I78Khz7VVuaLEYQwqk82ZVVk',
    appId: '1:338447448847:ios:9d26fcc4fb1c3db4a25c7a',
    messagingSenderId: '338447448847',
    projectId: 'redline-92e12',
    storageBucket: 'redline-92e12.appspot.com',
    iosBundleId: 'com.example.redLineTut.RunnerTests',
  );
}
